refractionPOINT/go-limacharlie

limacharlie/client.go
limacharlie/comms.go
limacharlie/comms_test.go
limacharlie/organization.go

- Basic Comms functions.
- Added support for custom URL roots in restRequest.
- Tweaked the REST request retry logic to be on par with the Python SDK (less retries on plain errors).
- Tweaked request serialization to more transparently send form requests with JSON-as-a-string.

Basic Comms support.

---

limacharlie/client.go
limacharlie/device.go
limacharlie/identification.go
limacharlie/organization.go
limacharlie/organization_test.go
limacharlie/sensor.go
limacharlie/sensor_test.go

Adding a bunch of accessors to the SDK for future use.

Adding basic listing of sensors.

---

limacharlie/comms.go
limacharlie/comms_test.go

Add some definitions for Message types.
Return MessageID from Posting a message.

Small tweaks to SDK for Comms commands.

---

limacharlie/comms.go

Add optional reason for closing a room
> Fix [#1]()

Add optional reason for closing a room

---

limacharlie/comms.go

Adding a new Message type `error`.
Adding a new Message type `cmdack` for acknowledged commands.

New message type "error".

---

limacharlie/sensor.go

Used wrong investigation ID.

---

limacharlie/client.go

Make RefreshJWT public

---

limacharlie/sync.go

Add JSON definitions to the Sync options to make it easier to serialize them.

JSON def for sync options.

---

limacharlie/sync.go
limacharlie/sync_test.go

Update SyncFetch to feature parity with python-limacharlie 

---

limacharlie/comms_link.go
limacharlie/comms_link_test.go

Add api to manipulate comms link

---

limacharlie/insight_objects.go
limacharlie/insight_objects_test.go

Add insight objects search
Closes https://github.com/refractionPOINT/tracking/issues/663

Add insight object search

---

limacharlie/output.go
limacharlie/sync.go

Init Exfil struct.

---

limacharlie/insight_objects.go

Location insight object type typo

---

limacharlie/go.mod
limacharlie/sync.go

Use 1.13 compatible code

---

limacharlie/comms.go

- Add markdown, json and yaml as message types

Add 3 new message types

---

limacharlie/output.go
limacharlie/output_test.go
limacharlie/sync.go

Define the yaml tags for Outputs.

Define tags for yaml output

---

limacharlie/exfil.go
limacharlie/fp_rule.go
limacharlie/integrity.go
limacharlie/net.go
limacharlie/sync.go

Sync fetch is reporting too much data in some cases.

Add yaml tags and remove mtd from sync fetch.

---

limacharlie/exfil.go
limacharlie/integrity_test.go
limacharlie/sync.go

More tweaks removing some fields from Sync.

More tag tweaks.

---

limacharlie/dr_rule.go
limacharlie/fp_rule.go
limacharlie/net.go
limacharlie/output.go
limacharlie/sync.go

Remove name from sync elements for compat with python.

Remove name from sync elements.

---

limacharlie/sync.go
limacharlie/sync_test.go

Handle a nil case in Sync and add a test.

Fix a nil case and add a test.

---

limacharlie/sync.go

The parent path did not propagate the previous relative path.

Fix the parent path in sync.

---

limacharlie/output.go

Fixing backwards compat with the Python Sync file config.

Fix sync format for Outputs.

---

limacharlie/sensor.go
limacharlie/sensor_test.go

Add accessor to get all tags in an org.

Add accessor to get all tags.

---

limacharlie/net.go

Set the OID in the Net Policy Add since it will go over the wire.

Set the OID in the Net Policy.

---

limacharlie/net.go
limacharlie/resource.go
limacharlie/sync.go
limacharlie/sync_test.go

Fix inverted eval and test

---

limacharlie/net.go
limacharlie/sync_test.go

Fix normalization of netpol for sync.

---

limacharlie/comms_test.go
limacharlie/integrity_test.go
limacharlie/organization.go
limacharlie/organization_test.go
limacharlie/resource.go
limacharlie/sync_test.go

Adding a function to list URLs for an Org.

Adding a GetURLs endpoint.

---

cloudbuild.yaml
limacharlie/payloads.go
limacharlie/payloads_test.go

Add payloads

---

limacharlie/organization.go

> Added functions to get the actual active sensors count and to assign an organization to a specific group
- [x ] New feature (non-breaking change that adds functionality)
> Fix [#1]()

DEF-868 Added functions GetOnlineCount and AddToGroup

---

limacharlie/organization.go

Ship new org parameters as Form data so that large config files don't go over the max URL size.

Change Query to Form  in the org request parameters

---

limacharlie/organization.go

refresh jwt for requests that take longer than an hour, like ext-plaso

refresh jwt for requests that take longer than an hour, like ext-plaso

---

limacharlie/sync.go
limacharlie/sync_test.go

A bug in the merge code lead to Hives being overwritten.

Fix hive merge bug and add tests
